# Generated by Django 5.2.7 on 2025-10-15 13:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('devoir', 'Devoir'), ('controle', 'Contrôle'), ('composition', 'Composition')], max_length=20, unique=True)),
                ('coefficient', models.DecimalField(decimal_places=1, default=1.0, help_text='Coefficient pour le calcul de la moyenne', max_digits=3)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Type d'Évaluation",
                'verbose_name_plural': "Types d'Évaluation",
                'ordering': ['coefficient'],
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('trimestre1', 'Trimestre 1'), ('trimestre2', 'Trimestre 2'), ('trimestre3', 'Trimestre 3')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_cloturee', models.BooleanField(default=False)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='academic.anneescolaire')),
            ],
            options={
                'verbose_name': 'Période',
                'verbose_name_plural': 'Périodes',
                'ordering': ['annee_scolaire', 'date_debut'],
                'unique_together': {('nom', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='MoyenneEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.DecimalField(decimal_places=2, help_text='Moyenne de la matière pour la période', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('nombre_notes', models.IntegerField(default=0)),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='academic.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='academic.matiere')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='grades.periode')),
            ],
            options={
                'verbose_name': 'Moyenne Élève',
                'verbose_name_plural': 'Moyennes Élèves',
                'ordering': ['eleve', 'periode', 'matiere'],
                'unique_together': {('eleve', 'matiere', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Note sur 20', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('date_evaluation', models.DateField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academic.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academic.matiere')),
                ('professeur', models.ForeignKey(help_text='Enseignant ayant saisi la note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to='users.professeur')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='grades.periode')),
                ('type_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='grades.typeevaluation')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-date_evaluation'],
                'unique_together': {('eleve', 'matiere', 'periode', 'type_evaluation')},
            },
        ),
    ]
