# Generated by Django 5.2.7 on 2025-10-15 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='valeur',
            field=models.DecimalField(decimal_places=2, help_text='Note sur 10 (école primaire)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
