# Generated by Django 5.2.7 on 2025-10-15 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_ecole'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ecole',
            field=models.ForeignKey(blank=True, help_text='École de rattachement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='academic.ecole'),
        ),
    ]
