# Generated by Django 5.2.7 on 2025-10-16 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_classe_unique_together_and_more'),
        ('users', '0002_user_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professeurs', to='academic.ecole', verbose_name='École'),
        ),
    ]
