# Generated by Django 5.2.7 on 2025-10-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom complet de l'école", max_length=200, unique=True)),
                ('sigle', models.CharField(blank=True, help_text='Sigle ou abréviation', max_length=20)),
                ('adresse', models.TextField(help_text="Adresse complète de l'école")),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ecoles/logos/')),
                ('devise', models.CharField(blank=True, help_text="Devise de l'école", max_length=200)),
                ('directeur', models.CharField(blank=True, help_text='Nom du directeur', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'École',
                'verbose_name_plural': 'Écoles',
                'ordering': ['nom'],
            },
        ),
    ]
