# Generated by Django 5.2.7 on 2025-10-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_ecole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['niveau', 'section'], 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classe',
            name='section',
            field=models.CharField(blank=True, help_text='Section (A, B, C, etc.) - optionnel', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(choices=[('ci', "CI - Cours d'Initiation"), ('cp', 'CP - Cours Préparatoire'), ('ce1', 'CE1 - Cours Élémentaire 1'), ('ce2', 'CE2 - Cours Élémentaire 2'), ('cm1', 'CM1 - Cours Moyen 1'), ('cm2', 'CM2 - Cours Moyen 2')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('niveau', 'section', 'annee_scolaire')},
        ),
    ]
