# Generated by Django 5.2.7 on 2025-10-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_classe_options_alter_classe_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('admis', 'Admis'), ('redouble', 'Redouble'), ('transfere', 'Transféré'), ('abandonne', 'Abandonné'), ('diplome', 'Diplômé')], default='actif', help_text="Statut actuel de l'élève dans le système", max_length=20),
        ),
    ]
