# Generated by Django 5.2.7 on 2025-10-16 15:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_eleve_statut'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='matiereclasse',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ecole',
            name='active',
        ),
        migrations.RemoveField(
            model_name='ecole',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ecole',
            name='directeur',
        ),
        migrations.RemoveField(
            model_name='ecole',
            name='sigle',
        ),
        migrations.RemoveField(
            model_name='ecole',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annees_scolaires', to='academic.ecole', verbose_name='École'),
        ),
        migrations.AddField(
            model_name='classe',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic.ecole', verbose_name='École'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='abonnement_actif',
            field=models.BooleanField(default=True, verbose_name='Abonnement actif'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='code',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Code unique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ecole',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ecole',
            name='date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AddField(
            model_name='ecole',
            name='directrice',
            field=models.CharField(default=1, max_length=200, verbose_name='Directrice/Directeur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ecole',
            name='max_eleves',
            field=models.IntegerField(default=500, verbose_name="Nombre maximum d'élèves"),
        ),
        migrations.AddField(
            model_name='ecole',
            name='max_professeurs',
            field=models.IntegerField(default=50, verbose_name="Nombre maximum d'enseignants"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='academic.ecole', verbose_name='École'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='academic.ecole', verbose_name='École'),
        ),
        migrations.AddField(
            model_name='matiereclasse',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres_classes', to='academic.ecole', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='libelle',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='adresse',
            field=models.TextField(verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='devise',
            field=models.CharField(default='Excellence, Discipline, Réussite', max_length=200),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ecoles/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='nom',
            field=models.CharField(max_length=200, verbose_name="Nom de l'école"),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='anneescolaire',
            unique_together={('libelle', 'ecole')},
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('niveau', 'section', 'annee_scolaire', 'ecole')},
        ),
        migrations.AlterUniqueTogether(
            name='eleve',
            unique_together={('matricule', 'ecole')},
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('code', 'ecole')},
        ),
        migrations.AlterUniqueTogether(
            name='matiereclasse',
            unique_together={('classe', 'matiere', 'ecole')},
        ),
    ]
